version: "3.9"

services:
  backend:
    build: ./backend
    container_name: rust-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data   # backend เก็บไฟล์ index/metadata ลง host
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: leptos-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

networks:
  default:
    driver: bridge
